"""Experimental TypeScript discovery (P20 slice 2, since 0.2.12).

tree-sitter lives in the optional `typescript` extra, so this whole module skips when it
is absent (a default Python-only install). CI installs it via `uv sync --all-extras`.
Run locally with: `uv sync --extra typescript && uv run pytest tests/test_typescript_discovery.py`.

These assertions are the reconciliation of the pre-parser predictions recorded in
`tests/fixtures/typescript/README.md` against what tree-sitter actually yields.
"""

from __future__ import annotations

from pathlib import Path

import pytest

pytest.importorskip("tree_sitter")
pytest.importorskip("tree_sitter_typescript")

from riskratchet.typescript import (
    discover_typescript,
    is_generated_typescript,
    iter_typescript_files,
)

FIXTURES = Path(__file__).parent / "fixtures" / "typescript"


def _discovered(name: str) -> dict[str, tuple[bool, str]]:
    """Map qualname -> (is_public, kind) for one fixture file."""
    fns = discover_typescript(FIXTURES / name, root=FIXTURES)
    return {fn.id.qualname: (fn.is_public, fn.kind) for fn in fns}


# Reconciled expectations (qualname -> (is_public, kind)).
EXPECTED: dict[str, dict[str, tuple[bool, str]]] = {
    "top_level.ts": {
        "add": (True, "function"),
        "greet": (False, "function"),
        "parseConfig": (True, "function"),
    },
    "methods.ts": {
        "Account.constructor": (True, "method"),
        "Account.deposit": (True, "method"),
        "Account.withdraw": (True, "method"),
        "Account.balance": (True, "method"),
        "Account.record": (True, "method"),
        "Account.total": (True, "method"),
    },
    "arrows.ts": {
        "double": (True, "arrow"),
        "clamp": (True, "arrow"),
        "makeCounter": (True, "arrow"),
        "makeCounter.increment": (False, "arrow"),
        "scaleAll": (True, "arrow"),
    },
    "components.tsx": {
        "Greeting": (True, "function"),
        "Counter": (True, "arrow"),
        "Counter.handleClick": (False, "arrow"),
    },
    "default_export.ts": {
        "buildHeaders": (False, "function"),
        "createClient": (True, "function"),
    },
    # Namespaced `Foo.bar` must not collide with the top-level `bar`.
    "namespaces.ts": {
        "Foo.bar": (True, "function"),
        "bar": (False, "function"),
    },
    # Abstract-class method keeps its class prefix; the abstract signature (no body) is excluded.
    "abstract.ts": {
        "Shape.concrete": (True, "method"),
    },
    # Anonymous default-export class still contributes a class segment.
    "anonymous_default.ts": {
        "default.m": (True, "method"),
    },
    # Export reachability via separate `export { … }` clauses.
    "reexport.ts": {
        "Svc.run": (True, "method"),
        "helper": (True, "function"),
        "hidden": (False, "function"),
    },
    # Non-exported class → internal method; `legacy` is a named function_expression.
    "internal_class.ts": {
        "Internal.helper": (False, "method"),
        "legacy": (False, "function"),
    },
    # `.mts` is discovered like `.ts`.
    "mts_module.mts": {
        "fromMjs": (True, "function"),
    },
}


@pytest.mark.parametrize("name", sorted(EXPECTED))
def test_discovery_matches_fixture(name: str) -> None:
    assert _discovered(name) == EXPECTED[name]


def test_generated_file_is_excluded() -> None:
    # `@generated` header + `*.pb.ts` name → zero functions, even though it has methods.
    assert discover_typescript(FIXTURES / "generated.pb.ts", root=FIXTURES) == []
    assert is_generated_typescript(Path("foo.pb.ts"), "")
    assert is_generated_typescript(Path("foo.ts"), "// @generated by tool\n")
    assert not is_generated_typescript(Path("foo.ts"), "export function f() {}\n")


def test_inline_callbacks_and_object_methods_are_skipped() -> None:
    # arrows.ts has an inline `.map(x => …)`; default_export.ts has an object-literal `get`.
    assert "scaleAll" in _discovered("arrows.ts")  # the named arrow is kept...
    arrows = discover_typescript(FIXTURES / "arrows.ts", root=FIXTURES)
    assert all("map" not in fn.id.qualname for fn in arrows)  # ...the inline callback is not
    default_export = {
        fn.id.qualname for fn in discover_typescript(FIXTURES / "default_export.ts", root=FIXTURES)
    }
    assert "createClient.get" not in default_export and "get" not in default_export


def test_async_and_span_are_captured() -> None:
    fns = {fn.id.qualname: fn for fn in discover_typescript(FIXTURES / "top_level.ts", root=FIXTURES)}
    assert fns["parseConfig"].is_async is True
    assert fns["add"].is_async is False
    assert fns["add"].span.start_line == 4 and fns["add"].span.end_line == 6


def test_is_async_holds_for_all_three_shapes() -> None:
    # async function declaration, async arrow, async method — not just declarations.
    fns = {fn.id.qualname: fn for fn in discover_typescript(FIXTURES / "async_variants.ts", root=FIXTURES)}
    assert fns["loadOne"].is_async is True  # function declaration
    assert fns["loadAll"].is_async is True  # arrow
    assert fns["Repo.deposit"].is_async is True  # method


def test_broken_file_is_skipped_and_reported() -> None:
    # tree-sitter is error-tolerant; a file with ERROR nodes must be skipped whole, not
    # walked for partial results — and the caller gets a signal, like the Python backend.
    errors: list[tuple[str, str]] = []
    result = discover_typescript(
        FIXTURES / "broken.ts", root=FIXTURES, on_error=lambda p, msg: errors.append((p.name, msg))
    )
    assert result == []
    assert errors == [("broken.ts", "syntax error")]


def test_valid_file_does_not_report_error() -> None:
    errors: list[tuple[str, str]] = []
    discover_typescript(
        FIXTURES / "top_level.ts", root=FIXTURES, on_error=lambda p, msg: errors.append((p.name, msg))
    )
    assert errors == []


def test_generated_marker_is_comment_anchored() -> None:
    # A leading comment marker counts; `@generated` in a string or trailing code does not.
    assert is_generated_typescript(Path("a.ts"), "// @generated by tool\n")
    assert is_generated_typescript(Path("a.ts"), "/** @generated */\n")
    assert is_generated_typescript(Path("a.ts"), "/*\n * @generated\n */\n")
    assert not is_generated_typescript(Path("a.ts"), 'const s = "@generated";\n')
    assert not is_generated_typescript(Path("a.ts"), "export const x = run(); // @generated later\n")
    assert is_generated_typescript(Path("a.pb.mts"), "")  # filename still wins
    assert is_generated_typescript(Path("a.gen.cts"), "")


def test_iter_typescript_files_finds_ts_tsx_and_mts() -> None:
    files = {p.name for p in iter_typescript_files([FIXTURES], root=FIXTURES)}
    assert {"top_level.ts", "components.tsx", "generated.pb.ts", "mts_module.mts"} <= files
    assert all(
        p.suffix in (".ts", ".tsx", ".mts", ".cts") for p in iter_typescript_files([FIXTURES], root=FIXTURES)
    )


def test_exclude_glob_is_respected() -> None:
    files = iter_typescript_files([FIXTURES], root=FIXTURES, exclude=["*.tsx"])
    assert all(p.suffix in (".ts", ".mts", ".cts") for p in files)
