/* eslint-disable */
// @generated by protoc-gen-ts. DO NOT EDIT.
// Fixture: generated code that SHOULD be excluded from discovery (mirrors how
// vendored/generated Python is excluded). The future backend is expected to skip
// this file entirely via the generated-code heuristic (header marker / filename),
// emitting ZERO functions — even though it contains function-shaped declarations.

export class Timestamp {
  seconds: number = 0;
  nanos: number = 0;

  static encode(message: Timestamp): Uint8Array {
    const buf = new Uint8Array(16);
    return buf;
  }

  static decode(input: Uint8Array): Timestamp {
    const msg = new Timestamp();
    return msg;
  }

  toJSON(): object {
    return { seconds: this.seconds, nanos: this.nanos };
  }
}
